version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: testmap
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "./data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: testmapdb
